name: ESLint
on:
  workflow_call:
    inputs:
        extensionName:
          description: 'Your extension name'
          required: true
          type: string
        onlishopVersion:
          description: |
            With the default `.auto`, the workflow tries to find a onlishop version using the onlishop-version action.

            For example, if the current ref is next-1234, it will try to find the ref next-1234 in onlishop/onlishop. If there's no matching ref, it will use onlishopVersionFallback
          required: false
          type: string
          default: '.auto'
        onlishopVersionFallback:
          required: false
          type: string
          default: trunk
        onlishop-repository:
          description: The onlishop repository to checkout
          type: string
          default: onlishop/onlishop

jobs:
  run:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: onlishop/github-actions/onlishop-version@main
        with:
          fallback: ${{ inputs.onlishopVersionFallback }}
          repo: ${{ inputs.onlishop-repository }}
        id: version
        if: ${{ inputs.onlishopVersion == '.auto' || inputs.onlishopVersion == '' }}
      - name: Clone Onlishop
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.onlishop-repository || 'onlishop/onlishop' }}
          ref: ${{ steps.version.outputs.onlishop-version || inputs.onlishopVersion }}
      - name: Clone Extension
        uses: actions/checkout@v5
        with:
          path: custom/plugins/${{ inputs.extensionName }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Install admin deps
        shell: bash
        working-directory: src/Administration/Resources/app/administration
        run: npm ci --no-audit --no-fund --prefer-offline

      - name: Install Plugin Dependencies
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm install --no-audit --no-fund --prefer-offline

      - name: Run ESLint
        working-directory: custom/plugins/${{ inputs.extensionName }}/src/Resources/app/administration
        run: npm run lint
